config/routes.rb
Rails.application.routes.draw do
  resources :vans do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:show, :edit, :update, :destroy]

  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "pages/profile", to: "pages#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :van
  validates :user, uniqueness: { scope: :van }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :vans, through: :bookings
  has_many :my_vans, class_name: 'Van'
  mount_uploader :photo, PhotoUploader
end

app/models/van.rb
class Van < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :users, through: :bookings
  has_many :bookings, dependent: :destroy


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :description, presence: true
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :photo, :photo_cache])
  end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @van = Van.find(params[:van_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @van = Van.find(params[:van_id])
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.user = current_user
    @booking.van = @van
    @booking.status = 'pending'
    if @booking.save
      redirect_to pages_profile_path
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @van = @booking.van
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    if @booking.save
      redirect_to pages_profile_path
    else
      render :new
    end
    authorize @booking
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to pages_profile_path
  end

  private

  def booking_params
    params_hash = params.require(:booking).permit(:user, :van, :status, :cost)
    params_hash[:start_date] = Date.strptime(params[:booking][:start_date], '%m/%d/%Y')
    params_hash[:end_date] = Date.strptime(params[:booking][:end_date], '%m/%d/%Y')
    return params_hash
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: :home
  def home
    @vans = Van.all.sample(10)
  end

  def profile

    @my_vans = current_user.my_vans
    @my_bookings = current_user.bookings
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/controllers/vans_controller.rb
class VansController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @vans = policy_scope(Van)

    @vans = Van.where.not(latitude: nil, longitude: nil)

    @markers = @vans.map do |van|
      {
        lat: van.latitude,
        lng: van.longitude,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def show
    @van = Van.find(params[:id])
    @booking = Booking.new
    authorize @van
  end

  def new
    @van = Van.new
    authorize @van
  end

  def create
    @van = Van.create(van_params)
    authorize @van
    @van.owner = current_user
    if @van.save
      redirect_to pages_profile_path
    else
      render :new
    end
  end

  def edit
    @van = Van.find(params[:id])
    authorize @van
  end

  def update
    @van = Van.find(params[:id])
    @van.update(van_params)
    if @van.save
      redirect_to van_path(@van)
    else
      render :new
    end
    authorize @van

  end

  def destroy
    @van = Van.find(params[:id])
    authorize @van
    @van.destroy
    redirect_to pages_profile_path
  end

  private

  def van_params
    params.require(:van).permit(:user, :description, :cost_per_night, :max_guest,:transmission_type, :toilet, :beds, :photo, :title, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="form-inputs">
  <%= simple_form_for [@van, @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="col-xs-12">
      <%= f.input :start_date %>
    </div>
    <div class="col-xs-12">
      <%= f.input :end_date %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<h1>Edit booking</h1>
<%= render 'form' %>

app/views/bookings/new.html.erb
<div class="container container-form">
  <div class="row">
    <div class="form-title">
      <h2>Make a Booking</h2>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="body-content">
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %> <!-- add this line -->
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/_bookings.html.erb
<div class="card">
 <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path van.photo, crop: :fill %>');">
  </div>
  <div class="card-description">
        <h2><%= link_to van.title, van_path(van) %></h2>
        <p>Start date:  <%= van.bookings[0].start_date %></p>
        <p>End date: <%= van.bookings[0].end_date %></p>
        <p>Total cost:  <%= van.bookings[0].cost %></p>
        <p>Owner: <%= van.owner.name %></p>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<%= render 'shared/carousel' %>
<div class="home-boarder">
</div>
<%= render 'shared/popular' %>
</div>
<!-- Latest compiled and minified CSS -->

<!--   <script>
    $(document).on('turbolinks:load', function() {
      $('#patient_date_of_birth_modal').datepicker({
        format: 'yyyy-mm-dd'
      }).on('hide', function(event) {
        event.preventDefault();
        event.stopPropagation();
      });
    });
  </script>
 -->

<%= javascript_pack_tag 'datepicker' %>

app/views/pages/profile.html.erb
<div class="profile-content">
<h1>My Profile</h1>
  <div class="home-boarder">
  </div>
<h2>My vans</h2>
  <div class="link-buttons">
    <%= link_to "Create a new van", new_van_path, class: "btn btn-primary" %>
  </div>
  <div class="profile-vans">
    <% @my_vans.each do |van| %>
      <div class="col-xs-12 col-md-3" >
        <%= render 'vans/card', van: van %>
      </div>
      <%end %>
  </div>

  <div class="home-boarder">
  </div>
<h2>My Bookings</h2>
<div class="profile-vans">
  <% @my_bookings.each do |booking| %>
    <div class="col-xs-12 col-md-4" >
      <%= render 'pages/bookings', van: booking.van %>
    </div>
    <%end %>
</div>

</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_url 'banner.jpg' %>');">
  <div class="banner-content">
    <form action="/vans" method='get'>
        <div class="row">
          <h2>Start your adventure - Book a Camper in</h2>
              <div id="custom-search-input">
                  <div class="input-group col-md-12">
                      <input type="text" name="address" id="city_address" class="form-control input-lg" placeholder="City" />
                      <span class="input-group-btn">
                          <button class="btn btn-info btn-lg" type="button">
                              <%= link_to vans_path do %>
                              <i class="glyphicon glyphicon-search"></i>
                              <% end %>
                          </button>
                      </span>
                  </div>
              </div>
            </div>
      <div class="input-daterange input-group" id="datepicker">
        <input type="text" name="start" />
        <span style="color:white">to</span>
        <input type="text" name="end" />
      </div>
    </form>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div class="content-home">
  <div class="container">
    <h2>TRAVEL, PEACE, LOVE AND TONY</h2>
    <div class="row-home">
      <% @vans.take(4).each do |van| %>
        <div class="col-xs-12 col-sm-3">
          <%= render 'vans/card', van: van %>
        </div>
      <% end  %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
 <div class="alert alert-info alert-dismissible" role="alert" style="position: absolute; top: 70px; width: 100vw">
   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
   <%= notice %>
 </div>
<% end %>
<% if alert %>
 <div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
   <%= alert %>
 </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_url 'banner.jpg' %>');">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-linkedin-in"></i></a>
  </div>
  <div class="footer-copyright">
  This footer is made with <i class="fa fa-heart"></i> from Ferdinand, Lito and Tony
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= current_page?(root_path) ? 'navbar-fixed-top' : ''  %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "campervan.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <%= link_to "List a van", new_van_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign Out", destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link", method: "delete" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= current_user.email%>
            <li>
              <%= link_to pages_profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_popular.html.erb
<div class="home-container" >
    <h3>A SELECTION OF VANS BASED ON YOUR TRAVEL PREFERENCES</h3>
    <div class="row">
      <% @vans.shuffle.take(4).each do |van| %>
        <div class="col-xs-12 col-sm-3">
          <%= render 'vans/card', van: van %>
        </div>
      <% end  %>
    </div>
</div>

app/views/shared/_van_form.html.erb
<!-- Latest compiled and minified CSS -->
<%= simple_form_for(@van) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <% if @van.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @van.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :cost_per_night %>
    <%= f.input :max_guest %>
    <%= f.input :toilet %>
    <%= f.input :beds %>
    <%= f.input :transmission_type, :collection => %w[Manual Automatic] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/vans/_card.html.erb
<div class="card">
  <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path van.photo, crop: :fill %>');">
  </div>
  <div class="card-description">
        <h2><%= link_to van.title, van_path(van) %></h2>
        <p>Cost per day:  <%= van.cost_per_night %></p>
        <p>Max guests: <%= van.beds %></p>
        <p>Transmission:  <%= van.transmission_type %></p>
        <p>Owner: <%= van.owner.name %></p>
  </div>
</div>

app/views/vans/_form.html.erb
<div class="form-inputs">
  <%= simple_form_for(@van) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-van">
    <div class="col-xs-12">
      <%= f.input :title, placeholder: "Give your Van a name.." %>
    </div>
    <div class="col-xs-12">
      <%= f.input :description, placeholder: "Describe your van.." %>
    </div>
    <div class="col-xs-12">
      <%= f.input :address, input_html: { id: "van_address" } %>
    </div>
    <div class="col-xs-12">
      <%= f.input :cost_per_night, placeholder: "Cost per night", label: "Price"%>
    </div>
    <div class="col-xs-6">
      <%= f.input :max_guest, :collection => %w[1 2 3 4] %>
    </div>
    <div class="col-xs-6">
      <%= f.input :beds, :collection => %w[1 2 3 4] %>
    </div>
    <div class="col-xs-12">
      <%= f.input :toilet %>
    </div>
    <div class="col-xs-12">
      <%= f.input :transmission_type, :collection => %w[Manual Automatic] %>
    </div>
    <div class="col-xs-12">
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    </div>
    <div class="col-xs-12">
      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-primary btn-van-creation" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/vans/edit.html.erb
<div class="container container-form">
  <div class="row">
    <div class="form-title">
      <h2>Edit your van post</h2>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/vans/index.html.erb
<div class="filter-button1">
  <button type="button" class="btn btn-danger">Location</button>
</div>
<div class="content">
  <div class="container">
    <div class="row">

      <% @vans.each do |van| %>
        <div class="col-xs-12 col-sm-4">
          <%= render 'card', van: van %>
        </div>
      <% end  %>

    </div>
  </div>


<div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>">

</div>
</div>

app/views/vans/new.html.erb
<div class="container container-form">
  <div class="row">
    <div class="form-title">
      <h2>Create a Van</h2>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/vans/show.html.erb
  <div class="banner show-page" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @van.photo,crop: :fill %>');"></div>
  <div class="listing">
    <div class="container">
      <!-- SECTION -->
      <div class="row">
        <!-- The Vehicle Summary -->
        <div class="col-md-8">
          <div class="listing-summary">
            <!-- avatar + vehicle title -->
            <div class="section">
              <div class="row">
                <div class="col-md-10 col-sm-9">
                  <h1 class="vehicle-title"><%= @van.title %></h1>
                  <h4 class="vehicle-address"><i class="fa fa-map-marker"></i><%= @van.address %></h4>
                </div>
               <div class="owner-profile col-md-2 col-sm-3">
                  <%= cl_image_tag @van.owner.photo, width: 80, height: 80, crop: :thumb, gravity: :face, class: "avatar" %>
                  <span class="owner-profile-name"><%= @van.owner.name %></span>
                </div>
              </div>
            </div>

            <hr>
            <!-- summary icons -->
            <div class="section">
              <div class="summary-icons">
                <div class="row">
                  <div class="col-xs-3">
                    <img src="<%= image_url 'vehicle-summary-icon-user-red.png' %>">
                    <p>Max Guests x<%=@van.max_guest %></p>
                  </div>
                  <div class="col-xs-3">
                    <img src="<%= image_url 'vehicle-summary-icon-bed-red.png'%>">
                    <p>Beds x<%=@van.beds %></p>
                  </div>
                  <div class="col-xs-3">
                    <img src="<%= image_url 'vehicle-summary-icon-toilet-red.png'%>">
                    <p>Toilet</p>
                  </div>
                  <div class="col-xs-3">
                    <img src="<%= image_url 'vehicle-summary-icon-transmission-auto-red.png'%>">
                    <p>Automatic</p>
                  </div>
                </div>
              </div>
            </div>
          </div></div>
        <div class="col-md-4">
          <!-- Listing-Pricing -->
          <div class="row">
            <div class="listing-pricing-container">
              <div class="listing-pricing">
              <!-- Section: Pricing Summary -->
                <div class="pricing-summary-section">
                  <span class="price-emphasis">€</span><span class="price-emphasis" data-id="averageRental"><%= @van.cost_per_night %></span> per day
                </div>
              <!-- Section: Pricing Breakdown & Book Button -->
                <%= simple_form_for [@van, @booking], class: 'pricing-form' do |f| %>
                  <fieldset class="col-xs-12">
                    <label>Pick up / Drop off</label>
                    <div class="input-wrapper input-underlined">
                      <i class="input-icon fa fa-calendar" aria-hidden="true"></i>
                      <div class="input-daterange input-group" id="datepicker">
                        <%= f.input :start_date, as: :string, input_html: {id: 'start-datepicker'} %>
                        <span>to</span>
                        <%= f.input :end_date, as: :string, input_html: {id: 'end-datepicker'} %>
                      </div>
                    </div>
                      <input type="hidden" name="booking[cost]" id="cost-params">
                  </fieldset>

                <div id="dates-available-wrapper">
                  <div class="col-xs-12">
                    <div class="pricing-row" data-price-row="rnt" style="">
                      <div style="float:left">
                        <span data-price-title="rnt">€<span data-id="averageRental"><%= @van.cost_per_night %></span> x <span data-id="duration">0</span> day(s) <a data-toggle="collapse" data-target="#extra-info-prices"></a></span><a data-toggle="collapse" data-target="#extra-info-prices"><i class="fa fa-question-circle toggle-extra-info"></i></a>
                        <div id="extra-info-prices" class="collapse extra-info">
                          <p data-price-breakdown="rnt"><p>Standard rate: $<%= @van.cost_per_night %> x 7 day(s)</p></p>
                          <p></p><p>Daily rates fluctuate based off seasonal availability.</p><p></p>
                        </div>
                      </div>

                      <div style="float: right">
                        <span style="font-size:18px">€<span data-price-rowtotal="rnt">0</span></span>
                      </div>
                    </div>
                  </div>

                <div class="col-xs-12">
                  <div class="pricing-row" style="border-bottom: 0" data-price-row="total">
                    <div style="float:left">
                      <span><b>Total</b>(GST Inc)</span>
                    </div>
                  <div style="float: right">
                    <span><span style="font-size:18px"><b>€<span data-price-rowtotal="total">0</span></b>
                    </span></span></div>
                  </div>
                </div>

                <div class="col-xs-12">
                  <div class="btn-request-booking-wrapper">
                    <div id="btn-request-booking" class="btn btn-block btn-request-booking">
                      <%= f.submit value: 'Make booking', input_html: {id: "btn-request-booking"} %>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Section: Blank Space -->

              <% end %>
              </div>
            </div>
          </div>        <!-- Listing-Pricing Ends-->
              </div>
      </div>

      <hr>
      <!-- SECTION -->
      <div class="row">
        <div class="col-md-8 listing-row">
          <div class="about">
            <div class="section">
              <h2>About the van</h2>
              <div class="user-editable-text"><%= @van.description %></div>
            </div>
          </div>
        <hr>
        </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'datepicker' %>

<%= link_to "Back", vans_path, class: "btn btn-primary" %>